teams:
  - name: github-maintainers
    maintainers:
      - hendrikebbers
    members:
      - rbarkerSL
      - nathanklick
      - andrewb1269hg
  - name: github-committers
    maintainers:
      - hendrikebbers
    members:
      - san-est
      - mishomihov00
  - name: community
    maintainers:
      - hendrikebbers
    members:
      - dmueller2001
      - popowycz
      - rbair23
      - samswag
      - travismccracken11
      - fakepaulbugeja
      - SimiHunjan
      - rwalworth
      - 0xivanov
      - AlfredoG87
      - AliNik4n
      - Ashe-Oro
      - BartoszSolkaArianelabs
      - CMiville42
      - Coiling-Dragon
      - Daniel-K-Ivanov
      - defigirlxo
      - ElijahLynn
      - Evdokia-Georgieva
      - IvanKavaldzhiev
      - Ivo-Yankov
      - JeffreyDallas
      - JivkoKelchev
      - Kirqkas
      - LionelChocron
      - Mark-Swirlds
      - MiroslavGatsanoga
      - Nana-EC
      - Neeharika-Sompalli
      - Neurone
      - OlegMazurov
      - Petyo-Lukanov
      - RAMTO
      - RaphaelMessian
      - Reccetech
      - RickyLB
      - Sheng-Long
      - SimiHunjan
      - StanislawMazowieckiAriane
      - StoyanDrumev
      - SvetBorislavov
      - VMN00B
      - a-saksena
      - acuarica
      - agadzhalov
      - alex-kuzmin-hg
      - allison-hashgraph
      - amckay7777
      - anastasiya-kovaliova
      - andrewb1269hg
      - annamariyaivanova
      - anthony-swirldslabs
      - ar-conmit
      - arianejasuwienas
      - arlanharris
      - arrusev
      - artemananiev
      - ata-nas
      - atul-hedera
      - atulmahamuni
      - beeradb
      - bguiz
      - bibitibooo1
      - bilyana-gospodinova
      - cweagans
      - dalvizu
      - david-bakin-sl
      - derektriley
      - devmab
      - dikel
      - dimitar-dinev
      - diptimahamuni
      - dmueller2001
      - donaldthibeau
      - dougvk
      - dr20240304
      - ebadiere
      - ed-marquez
      - edward-swirldslabs
      - edwin-greene
      - ElijahLynn
      - ericleponner
      - failfmi
      - fakepaulbugeja
      - georg-getz
      - georgi-l95
      - gregscullard
      - gsstoykov
      - ibankov
      - imalygin
      - instamenta
      - isaac-swirldslabs
      - ivaylogarnev-limechain
      - ivaylonikolov7
      - iwsimon
      - izik1
      - janaakhterov
      - jasperpotts
      - jayv80
      - jbair06
      - jeromy-cannon
      - jjohannes
      - jnels124
      - joan41868
      - joebxmoxx
      - jsync-swirlds
      - justin-atwell
      - kacper-koza-arianelabs
      - kenthejr
      - kfa-aguda
      - kfbr
      - kimbor
      - konstantinabl
      - kselveliev
      - lbaird
      - leninmehedy
      - litt3
      - lpetrovic05
      - lukelee-sl
      - m-swirldslabs
      - maptuhec
      - matteriben
      - mattp-swirldslabs
      - mb-swirlds
      - mgarbs
      - mgoelswirlds
      - mhess-swl
      - michalrozekariane
      - michielmulders
      - mishomihov00
      - mmalik-al
      - mustafauzunn
      - mxtartaglia-sl
      - nadezhdapopovaa
      - natanasow
      - nathanklick
      - netopyr
      - nickeynikolovv
      - nirbosl
      - nistanimirov
      - norbert-kulus-arianelabs
      - ochikov
      - ohsnapandrew
      - olsentorfinn
      - pathornteng
      - petreze
      - pjn82
      - pkaterskiLime
      - popowycz
      - poulok
      - povolev15
      - quiet-node
      - rbair23
      - rbarkerSL
      - reachtobhavesh
      - rickyrodmac
      - rsinha
      - rustyShacklefurd
      - rwalworth
      - ryan-swirldslabs
      - san-est
      - se7enarianelabs
      - sergmetelin
      - shezaan-hashgraph
      - steven-sheehy
      - stoqnkpL
      - stoyan-lime
      - stoyanov-st
      - svetoslav-nikol0v
      - svienot
      - tannerjfco
      - tdermendzhievv
      - theekrystallee
      - thenswan
      - thomas-swirlds-labs
      - tim-mchale
      - timo0
      - tinker-michaelj
      - tolorukooba
      - tomzhenghedera
      - travismccracken11
      - ty-swirldslabs
      - victor-yanev
      - vtronkov
      - web3-nomad
      - xin-hedera
      - yiliev0
      - yosiftouma
  - name: tsc
    maintainers:
      - hendrikebbers
    members:
      - popowycz
      - rbair23
      - stoqnkpL
      - Perseverance
      - lbaird
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - SeanBohan
      - daniela-barbosa
      - davidwboswell
      - hartm
      - minyu66
      - thelinuxfoundation
  - name: hiero-mirror-node-committers
    maintainers:
      - steven-sheehy
      - xin-hedera
    members:
      - bilyana-gospodinova
      - edwin-greene
      - IvanKavaldzhiev
      - jnels124
      - kselveliev
      - mgoelswirlds
      - nickeynikolovv
  - name: hiero-mirror-node-maintainers
    maintainers:
      - steven-sheehy
    members:
      - xin-hedera
  - name: hiero-local-node-committers
    maintainers:
      - georgi-l95
      - Nana-EC
      - natanasow
    members:
      - beeradb
      - Ivo-Yankov
      - konstantinabl
      - nathanklick
      - victor-yanev
  - name: hiero-local-node-maintainers
    maintainers:
      - Nana-EC
    members:
      - georgi-l95
      - natanasow
  - name: hiero-sdk-swift-maintainers
    maintainers:
      - RickyLB
    members:
      - SimiHunjan
  - name: hiero-sdk-swift-committers
    maintainers:
      - RickyLB
    members:
      - izik
      - rwalworth
  - name: hiero-sdk-rust-maintainers
    maintainers:
      - RickyLB
    members:
      - SimiHunjan
  - name: hiero-sdk-rust-committers
    maintainers:
      - RickyLB
    members:
      - agadzhalov
      - ivaylogarnev-limechain
      - ivaylonikolov7
  - name: hiero-sdk-java-maintainers
    maintainers:
      - 0xivanov
    members:
      - SimiHunjan
      - agadzhalov
  - name: hiero-sdk-java-committers
    maintainers:
      - 0xivanov
    members:
      - agadzhalov
  - name: hiero-sdk-js-maintainers
    maintainers:
      - SimiHunjan
    members:
      - ivaylonikolov7
      - agadzhalov
      - ivaylogarnev-limechain
  - name: hiero-sdk-js-committers
    maintainers:
      - SimiHunjan
    members:
      - agadzhalov
      - ivaylogarnev-limechain
      - ivaylonikolov7
  - name: hiero-sdk-cpp-maintainers
    maintainers:
      - rwalworth
    members:
      - SimiHunjan
  - name: hiero-sdk-cpp-committers
    maintainers:
      - rwalworth
    members:
      - gsstoykov
      - agadzhalov
  - name: hiero-sdk-tck-maintainers
    maintainers:
      - rwalworth
    members:
      - SimiHunjan
  - name: hiero-sdk-tck-committers
    maintainers:
      - rwalworth
    members:
      - ivaylogarnev-limechain
      - 0xivanov
      - agadzhalov
      - ivaylonikolov7
      - gsstoykov
      - RickyLB
  - name: hiero-sdk-go-maintainers
    maintainers:
      - SimiHunjan
    members:
      - 0xivanov
      - agadzhalov
      - gsstoykov
  - name: hiero-sdk-go-committers
    maintainers:
      - SimiHunjan
    members:
      - 0xivanov
      - agadzhalov
      - gsstoykov
  - name: hiero-gradle-conventions-maintainers
    maintainers:
      - rbarkerSL
      - andrewb1269hg
    members:
      - nathanklick
      - jjohannes
  - name: hiero-gradle-conventions-committers
    maintainers:
      - rbarkerSL
      - andrewb1269hg
    members:
      - mishomihov00
      - san-est
  - name: hiero-block-node-maintainers
    maintainers:
      - Nana-EC
    members:
      - AlfredoG87
      - mattp-swirldslabs
  - name: hiero-block-node-committers
    maintainers:
      - AlfredoG87
      - Nana-EC
    members:
      - rbarkerSL
      - georgi-l95
      - ata-nas
      - jsync-swirlds
      - san-est
      - rbair23
      - mishomihov00
      - jjohannes
      - a-saksena
      - CMiville42
      - mattp-swirldslabs
  - name: hiero-services-maintainers
    maintainers:
      - netopyr
    members:
      - Neeharika-Sompalli
      - tinker-michaelj
  - name: hiero-services-committers
    maintainers:
      - Neeharika-Sompalli
      - netopyr
      - tinker-michaelj
    members:
      - anastasiya-kovaliova
      - derektriley
      - Evdokia-Georgieva
      - ibankov
      - iwsimon
      - JivkoKelchev
      - kimbor
      - mhess-swl
      - MiroslavGatsanoga
      - petreze
      - povolev15
      - thomas-swirlds-labs
      - vtronkov
  - name: hiero-protobufs-maintainers
    maintainers:
      - netopyr
    members:
      - Neeharika-Sompalli
      - tinker-michaelj
  - name: hiero-protobufs-committers
    maintainers:
      - Neeharika-Sompalli
      - netopyr
      - tinker-michaelj
    members:
      - anastasiya-kovaliova
      - derektriley
      - Evdokia-Georgieva
      - ibankov
      - iwsimon
      - JivkoKelchev
      - kimbor
      - mhess-swl
      - MiroslavGatsanoga
      - petreze
      - povolev15
      - thomas-swirlds-labs
      - vtronkov
  - name: voting-candidates
    #All people that contributed to hashgraph repos and are approvide voters or candidates for TAC
    maintainers:
      - nathanklick
    members:
      - 0xivanov
      - AlfredoG87
      - AliNik4n
      - Ashe-Oro
      - BartoszSolkaArianelabs
      - CMiville42
      - Coiling-Dragon
      - Daniel-K-Ivanov
      - ElijahLynn
      - Evdokia-Georgieva
      - IvanKavaldzhiev
      - Ivo-Yankov
      - JeffreyDallas
      - JivkoKelchev
      - Kirqkas
      - Mark-Swirlds
      - MiroslavGatsanoga
      - Nana-EC
      - Neeharika-Sompalli
      - Neurone
      - OlegMazurov
      - Petyo-Lukanov
      - RAMTO
      - RaphaelMessian
      - Reccetech
      - RickyLB
      - Sheng-Long
      - SimiHunjan
      - StanislawMazowieckiAriane
      - StoyanDrumev
      - SvetBorislavov
      - VMN00B
      - a-saksena
      - acuarica
      - agadzhalov
      - alex-kuzmin-hg
      - allison-hashgraph
      - amckay7777
      - anastasiya-kovaliova
      - andrewb1269hg
      - annamariyaivanova
      - anthony-swirldslabs
      - ar-conmit
      - arianejasuwienas
      - arrusev
      - artemananiev
      - ata-nas
      - atul-hedera
      - beeradb
      - bibitibooo1
      - bilyana-gospodinova
      - cweagans
      - dalvizu
      - david-bakin-sl
      - derektriley
      - devmab
      - dikel
      - dimitar-dinev
      - donaldthibeau
      - dougvk
      - dr20240304
      - ebadiere
      - ed-marquez
      - edward-swirldslabs
      - edwin-greene
      - ericleponner
      - failfmi
      - georg-getz
      - georgi-l95
      - gregscullard
      - gsstoykov
      - hendrikebbers
      - ibankov
      - imalygin
      - instamenta
      - ivaylogarnev-limechain
      - ivaylonikolov7
      - iwsimon
      - izik1
      - janaakhterov
      - jasperpotts
      - jayv80
      - jeromy-cannon
      - jjohannes
      - jnels124
      - joan41868
      - jsync-swirlds
      - kacper-koza-arianelabs
      - kenthejr
      - kfa-aguda
      - kfbr
      - kimbor
      - konstantinabl
      - kselveliev
      - leninmehedy
      - litt3
      - lpetrovic05
      - lukelee-sl
      - maptuhec
      - matteriben
      - mattp-swirldslabs
      - mgarbs
      - mgoelswirlds
      - mhess-swl
      - michalrozekariane
      - michielmulders
      - mishomihov00
      - mmalik-al
      - mustafauzunn
      - mxtartaglia-sl
      - nadezhdapopovaa
      - natanasow
      - netopyr
      - nickeynikolovv
      - nirbosl
      - nistanimirov
      - norbert-kulus-arianelabs
      - ochikov
      - pathornteng
      - petreze
      - pjn82
      - pkaterskiLime
      - poulok
      - povolev15
      - quiet-node
      - rbair23
      - rbarkerSL
      - reachtobhavesh
      - rickyrodmac
      - rsinha
      - rustyShacklefurd
      - rwalworth
      - san-est
      - se7enarianelabs
      - sergmetelin
      - shezaan-hashgraph
      - steven-sheehy
      - stoqnkpL
      - stoyan-lime
      - stoyanov-st
      - svetoslav-nikol0v
      - svienot
      - tannerjfco
      - tdermendzhievv
      - theekrystallee
      - thenswan
      - thomas-swirlds-labs
      - tim-mchale
      - timo0
      - tinker-michaelj
      - tolorukooba
      - tomzhenghedera
      - ty-swirldslabs
      - victor-yanev
      - vtronkov
      - web3-nomad
      - xin-hedera
      - yiliev0
      - yosiftouma
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      tsc: maintain
      github-maintainers: maintain
    visibility: public
  - name: hiero-website
    teams:
      community: triage
      tsc: maintain
      github-maintainers: maintain
    visibility: public
  - name: hiero
    teams:
      tsc: maintain
      github-maintainers: maintain
    visibility: public
  - name: tsc
    teams:
      tsc: maintain
      github-maintainers: maintain
    visibility: public
  - name: awesome-contributions
    teams:
      community: triage
      github-maintainers: maintain
    visibility: public
  - name: .github
    teams:
      tsc: maintain
      github-maintainers: maintain
    visibility: public
  - name: hiero-sdk-cpp
    teams:
      tsc: maintain
      github-maintainers: admin
      github-committers: write
      hiero-sdk-cpp-maintainers: maintain
      hiero-sdk-cpp-committers: write
    visibility: public
  - name: hiero-sdk-tck
    teams:
      tsc: maintain
      github-maintainers: admin
      github-committers: write
      hiero-sdk-tck-maintainers: maintain
      hiero-sdk-tck-committers: write
    visibility: public
  - name: hiero-gradle-conventions
    teams:
      tsc: maintain
      github-maintainers: admin
      github-committers: write
      hiero-gradle-conventions-maintainers: maintain
      hiero-gradle-conventions-committers: write
    visibility: public
  - name: hiero-sdk-go
    teams:
      tsc: maintain
      github-maintainers: admin
      github-committers: write
      hiero-sdk-go-maintainers: maintain
      hiero-sdk-go-committers: write
    visibility: public
